; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	my_strlen
PUBLIC	main
pdata	SEGMENT
$pdata$my_strlen DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$my_strlen
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+21
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG8927	DB	'hello world', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$my_strlen DD 010901H
	DD	02209H
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\strlen\main.c
; Line 11
$LN3:
	sub	rsp, 40					; 00000028H
; Line 12
	lea	rcx, OFFSET FLAT:$SG8927
	call	my_strlen
; Line 13
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv67 = 0
eos$ = 8
str$ = 32
my_strlen PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\strlen\main.c
; Line 4
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 5
	mov	rax, QWORD PTR str$[rsp]
	mov	QWORD PTR eos$[rsp], rax
$LN2@my_strlen:
; Line 6
	mov	rax, QWORD PTR eos$[rsp]
	movsx	eax, BYTE PTR [rax]
	mov	DWORD PTR tv67[rsp], eax
	mov	rax, QWORD PTR eos$[rsp]
	inc	rax
	mov	QWORD PTR eos$[rsp], rax
	cmp	DWORD PTR tv67[rsp], 0
	je	SHORT $LN3@my_strlen
	jmp	SHORT $LN2@my_strlen
$LN3@my_strlen:
; Line 7
	mov	rax, QWORD PTR str$[rsp]
	mov	rcx, QWORD PTR eos$[rsp]
	sub	rcx, rax
	mov	rax, rcx
	inc	rax
; Line 8
	add	rsp, 24
	ret	0
my_strlen ENDP
_TEXT	ENDS
END
