; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	f1
PUBLIC	f2
PUBLIC	f3
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
f3	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\mul\imul.c
; Line 15
	imul	eax, ecx, 17
; Line 16
	ret	0
f3	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
f2	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\mul\imul.c
; Line 10
	imul	eax, ecx, 28
; Line 11
	ret	0
f2	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
f1	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\mul\imul.c
; Line 5
	imul	eax, ecx, 7
; Line 6
	ret	0
f1	ENDP
_TEXT	ENDS
END
