; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+80
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	011319H
	DD	04204H
	DD	imagerel __GSHandlerCheck
	DD	018H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
s$ = 0
__$ArrayPad$ = 24
main	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\structure\nest.c
; Line 18
$LN3:
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 20
	mov	BYTE PTR s$[rsp], 1
; Line 21
	mov	DWORD PTR s$[rsp+4], 2
; Line 22
	mov	DWORD PTR s$[rsp+8], 100		; 00000064H
; Line 23
	mov	DWORD PTR s$[rsp+12], 101		; 00000065H
; Line 24
	mov	BYTE PTR s$[rsp+16], 3
; Line 25
	mov	DWORD PTR s$[rsp+20], 4
; Line 27
	xor	eax, eax
; Line 28
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
