; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	my_srand
PUBLIC	my_rand
_BSS	SEGMENT
rand_state DD	01H DUP (?)
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
my_rand	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\random\fake_rand.c
; Line 15
	imul	eax, DWORD PTR rand_state, 1664525	; 0019660dH
	mov	DWORD PTR rand_state, eax
; Line 16
	mov	eax, DWORD PTR rand_state
	add	eax, 1013904223				; 3c6ef35fH
	mov	DWORD PTR rand_state, eax
; Line 17
	mov	eax, DWORD PTR rand_state
	and	eax, 32767				; 00007fffH
; Line 18
	ret	0
my_rand	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
init$ = 8
my_srand PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\random\fake_rand.c
; Line 9
	mov	DWORD PTR [rsp+8], ecx
; Line 10
	mov	eax, DWORD PTR init$[rsp]
	mov	DWORD PTR rand_state, eax
; Line 11
	ret	0
my_srand ENDP
_TEXT	ENDS
END
