; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\ray\Desktop\Disassembly\point\global_var.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_product:DWORD
COMM	_sum:DWORD
$SG2696	DB	'sum = %d', 0aH, 'product = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_f1
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_sum$ = 16						; size = 4
_product$ = 20						; size = 4
_f1	PROC
; File c:\users\ray\desktop\disassembly\point\global_var.c
; Line 5
	mov	ecx, DWORD PTR _y$[esp-4]
	mov	eax, DWORD PTR _x$[esp-4]
	lea	edx, DWORD PTR [eax+ecx]
; Line 6
	imul	eax, ecx
	mov	ecx, DWORD PTR _product$[esp-4]
	push	esi
	mov	esi, DWORD PTR _sum$[esp]
	mov	DWORD PTR [esi], edx
	mov	DWORD PTR [ecx], eax
	pop	esi
; Line 7
	ret	0
_f1	ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 14
	push	56088					; 0000db18H
	push	579					; 00000243H
	push	OFFSET $SG2696
	mov	DWORD PTR _sum, 579			; 00000243H
	mov	DWORD PTR _product, 56088		; 0000db18H
	call	_printf
	add	esp, 12					; 0000000cH
; Line 15
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
