; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	__imp_CreateFileA:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+68
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG95360 DB	'file.txt', 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	0a204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
fh$ = 64
main	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\bit_op\winNT.c
; Line 4
$LN3:
	sub	rsp, 88					; 00000058H
; Line 7
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 4
	xor	r9d, r9d
	mov	r8d, 1
	mov	edx, -1073741824			; c0000000H
	lea	rcx, OFFSET FLAT:$SG95360
	call	QWORD PTR __imp_CreateFileA
	mov	QWORD PTR fh$[rsp], rax
; Line 8
	xor	eax, eax
; Line 9
	add	rsp, 88					; 00000058H
	ret	0
main	ENDP
_TEXT	ENDS
END
