; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	f
PUBLIC	main
pdata	SEGMENT
$pdata$f DD	imagerel $LN3
	DD	imagerel $LN3+23
	DD	imagerel $unwind$f
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+21
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$f DD	010801H
	DD	02208H
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\bit_op\Set&Rm.c
; Line 16
$LN3:
	sub	rsp, 40					; 00000028H
; Line 17
	mov	ecx, 305419896				; 12345678H
	call	f
; Line 18
	xor	eax, eax
; Line 19
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
rt$ = 0
a$ = 32
f	PROC
; File C:\Users\82595\Documents\GitHub\Disassembly\bit_op\Set&Rm.c
; Line 8
$LN3:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 9
	mov	eax, DWORD PTR a$[rsp]
	mov	DWORD PTR rt$[rsp], eax
; Line 12
	mov	eax, DWORD PTR rt$[rsp]
; Line 13
	add	rsp, 24
	ret	0
f	ENDP
_TEXT	ENDS
END
