; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\ray\Desktop\Disassembly\_goto\main.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2637	DB	'hello world', 0aH, 00H
	ORG $+3
$SG2639	DB	'hello hack', 0aH, 00H
$SG2640	DB	'OMG!', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\users\ray\desktop\disassembly\_goto\main.c
; Line 10
	push	ebp
	mov	ebp, esp
; Line 11
	push	OFFSET $SG2637
	call	_printf
	add	esp, 4
; Line 12
	jmp	SHORT $exit$2638
; Line 13
	push	OFFSET $SG2639
	call	_printf
	add	esp, 4
$exit$2638:
; Line 15
	push	OFFSET $SG2640
	call	_printf
	add	esp, 4
; Line 16
	xor	eax, eax
; Line 17
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
